# https://docs.gradle.org/current/userguide/version_catalogs.html#sec::toml-dependencies-format

[versions]
assertj = "3.27.7"
jackson = "3.2.2"
jspecify = "1.0.1"
junit = "6.1.3"
maven-publish = "0.37.0"
errorprone-plugin = "5.1.0"
errorprone = "2.50.0"
nullaway = "0.14.1"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
